[pytest]
minversion = "9.0.2"
testpaths = ["tests"]
addopts = [
  # Gives a quick list of why tests failed, were skipped, or xfailed,
  "-ra",
  # Quieter output
  "-q",
]
markers = [
  "typecheck: type-checker compatibility tests (pyright, mypy, ty)",
]
